project_name: 'modeling-mrcnn'
task: 'segment_project-mrcnn'
num_classes: 2
n_epochs: 200
accelerator: 'gpu'
devices: '9'
monitor_metric: 'val_mask_map_50'
box_detection_per_img: 539
hidden_layer: 1024
mask_threshold: 0.6
min_score: 0.3
load_from_ckpt: 'lightning_logs/version_34/checkpoints/mrcnn-epoch=38-step=312-train_loss=0.8582.ckpt'
optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 3e-4

scheduler: 'cosine_annealing_warmup.CosineAnnealingWarmupRestarts'
scheduler_kwargs:
  first_cycle_steps: 50
  cycle_mult: 1.0
  max_lr: 3e-4
  min_lr: 1e-5
  warmup_steps: 1
  gamma: 1.0
  last_epoch: -1


  
mlflow_config:
  run_name: 'mrcnn'
  experiment_name: 'mrcnn'
  tracking_uri: 'http://mlflow:5000'

data_config:
  data_path: '../../shared_data/SatelliteTo3D-Datasets/segment_project.v2i.coco-segmentation'
  batch_size: 8
  n_workers: 2
  image_size: 512
  processor_image_size: 640
  dataset_name: 'bisd'
